#!/usr/bin/env python3
"""Regenerate `tickers_slim.rs` from `tickers.rs`.

The slim table is the full table intersected with the tickers that can actually
be delivered — i.e. the keys of `XSTOCK_MINTS`. It is generated rather than
maintained so that the two can never disagree, and committed rather than built
by a `build.rs` so that what ships stays readable to anyone auditing the
program. `tickers::consistency` fails the build if this file is stale.

    python3 scripts/slim-tickers.py
"""
import re, pathlib

SRC = pathlib.Path(__file__).resolve().parent.parent / "programs/quid/src"
full = (SRC / "tickers.rs").read_text()
deliverable = set(re.findall(r'"([^"]+)" =>', re.search(
    r'XSTOCK_MINTS[^{]*\{(.*?)\n\};', (SRC / "etc.rs").read_text(), re.S).group(1)))

out, kept = [], {}
for name, body in re.findall(r'pub static (\w+_MAP)[^{]*\{(.*?)\n\};', full, re.S):
    rows = [l for l in body.split("\n") if "=>" in l]
    # Only the US equity table is large enough to be worth cutting; the others
    # are a few hundred bytes each and every one of their rows is reachable.
    if name.startswith("US_EQUITIES"):
        rows = [r for r in rows if re.search(r'"([^"]+)" =>', r).group(1) in deliverable]
    kept[name] = len(rows)
    decl = re.search(r'(pub static %s[^{]*\{)' % name, full).group(1)
    out.append(decl + "\n" + "\n".join(rows) + "\n};\n")

(SRC / "tickers_slim.rs").write_text(
    "//! GENERATED by `scripts/slim-tickers.py` — do not edit by hand.\n"
    "//!\n"
    "//! The deliverable subset of `tickers.rs`: every ticker Backed Finance\n"
    "//! actually issues an xStock for, plus the commodity, metal, rate and FX\n"
    "//! feeds, which are small enough that trimming them would save nothing.\n"
    "//! See `tickers.rs` for why this exists.\n\nuse phf::phf_map;\n\n"
    + "\n".join(out))
print("deliverable tickers:", len(deliverable))
for k, v in kept.items(): print(f"  {k}: {v}")
