[package]
name = "quid-sgxs-sign"
license = "PolyForm-Noncommercial-1.0.0"
authors = { workspace = true }
edition = { workspace = true }
version = { workspace = true }
publish = false

[[bin]]
name = "gen-signer"
path = "src/bin/gen-signer.rs"

[dependencies]

# --- QU!D --- #

quid-byte-array = { workspace = true }
quid-crypto = { workspace = true }
quid-enclave = { workspace = true }
quid-hex = { workspace = true }
quid-sha256 = { workspace = true }

# --- WORKSPACE --- #

anyhow = { workspace = true }
rsa = { workspace = true }
sgxs = { workspace = true }
